import 'package:flutter/material.dart';
import './models/category.dart';
import 'models/meals.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Italian',
    color: Colors.black,
  ),
  Category(
    id: 'c2',
    title: 'Quick & Easy',
    color: Colors.black,
  ),
  Category(id: 'c3', title: 'Hamburgers', color: Colors.black),
  Category(
    id: 'c4',
    title: 'German',
    color: Colors.black,
  ),
  Category(
    id: 'c5',
    title: 'Light & Lovely',
    color: Colors.black,
  ),
  Category(
    id: 'c6',
    title: 'Exotic',
    color: Colors.black,
  ),
  Category(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.black,
  ),
  Category(
    id: 'c8',
    title: 'Asian',
    color: Colors.black,
  ),
  Category(id: 'c9', title: 'French', color: Colors.black),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Colors.black,
  ),
  Category(
    id: 'c9',
    title: 'French',
    color: Colors.black,
  ),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Colors.black,
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c2',
    ],
    title: 'Spaghetti with Tomato Sauce',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg/800px-Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg',
    duration: 20,
    ingredients: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.'
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
    ],
    title: 'Toast Hawaii',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg',
    duration: 10,
    ingredients: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c2',
      'c3',
    ],
    title: 'Classic Hamburger',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/10/23/18/05/burger-500054_1280.jpg',
    duration: 45,
    ingredients: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
    ],
    title: 'Wiener Schnitzel',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/03/31/19/29/schnitzel-3279045_1280.jpg',
    duration: 60,
    ingredients: [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices'
    ],
    steps: [
      'Tenderize the veal to about 2–4mm, and salt on both sides.',
      'On a flat plate, stir the eggs briefly with a fork.',
      'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
      'Heat the butter and oil in a large pan (allow the fat to get very hot) and fry the schnitzels until golden brown on both sides.',
      'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
      'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
      'Place the schnitzels on awarmed plate and serve garnishedwith parsley and slices of lemon.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2'
          'c5',
      'c10',
    ],
    title: 'Salad with Smoked Salmon',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2016/10/25/13/29/smoked-salmon-salad-1768890_1280.jpg',
    duration: 15,
    ingredients: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    steps: [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
      'c10',
    ],
    title: 'Delicious Orange Mousse',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2017/05/01/05/18/pastry-2274750_1280.jpg',
    duration: 240,
    ingredients: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Pancakes',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 20,
    ingredients: [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    steps: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: 'Creamy Indian Chicken Curry',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/06/18/16/05/indian-food-3482749_1280.jpg',
    duration: 35,
    ingredients: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c9',
    ],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/08/07/21/07/souffle-412785_1280.jpg',
    duration: 45,
    ingredients: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Asparagus Salad with Cherry Tomatoes',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 30,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
      id: 'm11',
      categories: ['c8'],
      title: 'Butter Chicken',
      imageUrl:
          'https://media.istockphoto.com/photos/butter-chicken-served-with-homemade-indian-naan-bread-picture-id618457124?s=612x612',
      ingredients: [
        'Raw Chicken2',
        'tsp Red Chilli Powder',
        '2 tsp Ginger-Garlic Paste,',
        '2 tsp Salt,',
        '2 tsp Lemon Juice,',
        '1/2 cup Curd,',
        '1/2 tsp Garam Masala,',
        '1 tsp Kasuri Methi,',
        '2 tsp Mustard OilFor gravy,',
        '2 tsp Oil,',
        '2 to taste Butter Cubes,',
        '3 gram Cloves1 Cinnamon Stick,',
        'sliced1 tsp Mace7 Cardamom4 Tomatoes,',
        'chopped1 tsp,',
        'Ginger1 tsp ,',
        'Ginger-Garlic Paste1,',
        '1/2 tsp Red Chilli Powder,',
        '1 tsp Kasuri Methi,',
        '2 tsp Honey,',
        '1 Green Chilli,',
        '2 tsp Cardamom Powder',
        '1 tbsp Cream',
      ],
      steps: [
        'In a mixing bowl, put raw chicken pieces and add salt, red chilli powder, ginger garlic paste and lemon juice',
        'Refrigerate for about 15-20 minutes',
        'Now add curd to the refrigerated mix. Followed by salt, ginger garlic paste, red chilli powder, garam masala, kasuri methi and mustard oil. Mix well and refrigerate again for an hour.',
        'Roast the marinated chicken in an oven for about 30 minutes until it is three-fourth done.'
      ],
      duration: 45,
      complexity: Complexity.Challenging,
      affordability: Affordability.Pricey,
      isGlutenFree: true,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: false),
  Meal(
      id: 'm12',
      categories: [
        'c2',
        'c7',
        'c8',
      ],
      title: 'Poha',
      imageUrl:
          'https://www.indianveggiedelight.com/wp-content/uploads/2022/07/poha.jpg',
      ingredients: [
        '2 tablespoons oil,',
        '1.5 cups poha (flattened rice) thick to medium flakes,',
        '2-3 tablespoons peanuts,',
        '½ teaspoon cumin seeds,',
        '½ teaspoon mustard seeds',
        '2-3 green chilies finely chopped',
        '1 sprig curry leaves',
        '1 medium onion (about ¾ cup), finely chopped',
        '1 medium potato cut int ½ inch pieces, (or ½ cup mixed veggies)',
        '½ teaspoon turmeric',
        '½ teaspoon sugar optional',
        'salt to taste'
      ],
      steps: [
        'Gently rinse poha in a colander under running water 2-3 times until they soften and then drain out all the water. When you press with your fingers, it should break easily. Keep it aside',
        'Heat oil in a Kadai. Add raw peanuts and fry until they turn golden brown. Remove the peanuts to a plate and set them aside'
            'In the same kadai, add mustard and cumin seeds and let them splutter',
        'Then add green chilies, curry leaves, and chopped onion. Saute until onions turn soft and translucent.',
        'Next, add cubed potatoes (or mixed vegetables) and cook for 2-3 minutes.',
        'Cover and cook on medium-low heat till the potatoes are soft and perfectly cooked. Sprinkle some water if required',
        'Add rinsed and drained poha, turmeric, salt, and sugar. Mix everything well',
        'If you feel the poha is too dry, sprinkle some water all over. Cover it with a lid and cook for 2 minutes on low heat',
        'Turn off the heat. Add the lemon juice and roasted peanuts, and give a quick mix. Garnish with coriander leaves'
      ],
      duration: 30,
      complexity: Complexity.Simple,
      affordability: Affordability.Pricey,
      isGlutenFree: true,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: true),
  Meal(
      id: 'm13',
      categories: [
        'c2',
        'c7',
        'c8',
      ],
      title: 'Misal',
      imageUrl:
          'https://hebbarskitchen.com/wp-content/uploads/mainPhotos/misal-pav-recipe-how-to-make-maharashtrian-misal-pav-recipe-1-769x1024.jpeg',
      ingredients: [
        '8 to 10 pav (bread rolls),',
        '½ cup finely chopped onions',
        '½ cup finely chopped tomatoes optional',
        '½ to 1 cup thick sev or farsan (chiwda), fried savory snack mixture',
        '1 lemon or lime quartered or diced',
        '⅓ cup chopped coriander leaves',
        '½ cup Curd or yogurt, beaten, optional'
            'salt as required',
        '1 teaspoon mustard seeds',
        '1 teaspoon cumin seeds',
        '10 to 12 curry leaves',
        '1 to 1.5 tablespoon Godaa or kala masala',
        '½ teaspoon red chili pow,',
        '¼ teaspoon turmeric powd,',
        '1 teaspoon Coriander Powder',
        '1 teaspoon cumin powder',
        '1.5 teaspoons tamarind – soaked in ⅓ or ½ cup water or 2 to 3 kokums',
        '¾ to 1 cup water or add as required',
        '3 tablespoons oil'
      ],
      steps: [
        'Rinse 2 cups of moth bean sprouts first in running water a couple of times.',
        'Drain the water from the sprouts very well and add the sprouts to a 3 litre stove-top pressure cooker'
            'Also add 2 medium-sized potatoes (chopped) and ¼ teaspoon turmeric powder as required in the pressure cooker',
        ' Add 3 cups water or as required. Note that the water should be covering the matki sprouts and potatoes about 2 inches above. The quantity of water will vary with the depth and length of the pressure cooker, so add more water if needed',
        'Add ½ teaspoon of salt or as required',
        'Pressure cook for 2 to 3 whistles on medium heat. When the pressure falls or reduces on its own then only open the lid of the pressure cooker',
        'In a small bowl, soak the tamarind in ⅓ or ½ cup warm or hot water for 25 to 30 minutes',
        'Squeeze the tamarind and extract the pulp. Keep the tamarind pulp aside. We will be using it later',
        'Measure and keep all the spices ready',
        ' Heat 3 tablespoons of oil in another pan. Crackle 1 teaspoon of mustard seeds first at low to medium-low heat',
        'Then add 1 teaspoon of cumin seeds. Saute for some seconds till the cumin gets golden',
        'Add one large or medium-sized onion (chopped)',
        'Drain the water from the pressure-cooked matki sprouts and potatoes with a colander',
        'Take the steaming hot usal in 4 to 5 serving bowls or shallow plates.',
        'Then top the usal with chopped coriander leaves.',
        ' Serve a side of some lemon wedges, chopped onions and mix farsan/sev/chiwda. Serve the Misal in a bowl or a plate with pav buns. You can also serve misal with a side of buttermilk (chass) or curd (yogurt) as it balances the spiciness of the usal'
      ],
      duration: 30,
      complexity: Complexity.Simple,
      affordability: Affordability.Pricey,
      isGlutenFree: true,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: true),
];
